// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	/// <summary>
	/// Продукт
	/// </summary>
	[Table("goods")]
	public class Good
	{
		/// <summary>
		/// Уникальный идентификатор
		/// </summary>
		[Column("id"         , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id          { get; set; } // bigint
		/// <summary>
		/// Название
		/// </summary>
		[Column("name"       , CanBeNull    = false                                                             )] public string  Name        { get; set; } = null!; // character varying(200)
		/// <summary>
		/// Краткое описание
		/// </summary>
		[Column("description"                                                                                   )] public string? Description { get; set; } // text

		#region Associations
		/// <summary>
		/// goods_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(PurchaseXrefGood.GoodsId))]
		public IEnumerable<PurchaseXrefGood> PurchaseXrefGoods { get; set; } = null!;
		#endregion
	}
}
