// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	/// <summary>
	/// Жильцы в доме (в локации)
	/// </summary>
	[Table("house_xref_user")]
	public class HouseXrefUser
	{
		/// <summary>
		/// Уникальный идентификатор
		/// </summary>
		[Column("id"      , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long Id      { get; set; } // bigint
		/// <summary>
		/// Идентификатор дома
		/// </summary>
		[Column("house_id"                                                                                  )] public long HouseId { get; set; } // bigint
		/// <summary>
		/// Идентификатор пользователя
		/// </summary>
		[Column("user_id"                                                                                   )] public long UserId  { get; set; } // bigint

		#region Associations
		/// <summary>
		/// house_xref_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(HouseId), OtherKey = nameof(DataModel.House.Id))]
		public House House { get; set; } = null!;

		/// <summary>
		/// user_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.Id))]
		public User User { get; set; } = null!;
		#endregion
	}
}
