// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	/// <summary>
	/// Детализация покупки
	/// </summary>
	[Table("purchase_xref_goods")]
	public class PurchaseXrefGood
	{
		/// <summary>
		/// Уникальный идентификатор
		/// </summary>
		[Column("id"         , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long     Id         { get; set; } // bigint
		/// <summary>
		/// Идентификатор покупки
		/// </summary>
		[Column("purchase_id"                                                                                  )] public long     PurchaseId { get; set; } // bigint
		/// <summary>
		/// Идентификатор товара
		/// </summary>
		[Column("goods_id"                                                                                     )] public long     GoodsId    { get; set; } // bigint
		/// <summary>
		/// Срок годности
		/// </summary>
		[Column("expire_date"                                                                                  )] public DateTime ExpireDate { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// goods_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(GoodsId), OtherKey = nameof(Good.Id))]
		public Good Goods { get; set; } = null!;

		/// <summary>
		/// purchase_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(PurchaseId), OtherKey = nameof(DataModel.Purchase.Id))]
		public Purchase Purchase { get; set; } = null!;

		/// <summary>
		/// purchase_xref_goods_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Recycle.PurchaseXrefGoodsId))]
		public IEnumerable<Recycle> Recycles { get; set; } = null!;
		#endregion
	}
}
