// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	/// <summary>
	/// Хранилище refresh-токенов пользователей
	/// </summary>
	[Table("user_xref_refresh_token")]
	public class UserXrefRefreshToken
	{
		/// <summary>
		/// Уникальный идентификатор записи
		/// </summary>
		[Column("id"           , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id           { get; set; } // bigint
		/// <summary>
		/// Идентификатор пользователя
		/// </summary>
		[Column("user_id"                                                                                        )] public long    UserId       { get; set; } // bigint
		/// <summary>
		/// Refresh-токен пользователя
		/// </summary>
		[Column("refresh_token"                                                                                  )] public string? RefreshToken { get; set; } // character varying(50)

		#region Associations
		/// <summary>
		/// user_refresh_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.Id))]
		public User User { get; set; } = null!;
		#endregion
	}
}
